name: Release (Develop)

on:
  push:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: jerray/publish-docker-action@master
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        file: dockerfiles/Dockerfile.self-contained
        repository: containrrr/watchtower
        tags: latest-dev
